# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=11)),
                ('descricao', models.TextField()),
                ('sigla', models.CharField(max_length=10)),
                ('ano', models.DateField()),
                ('logo', models.ImageField(upload_to='')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_evento', to='eventos.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festa_evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Pessoa')),
                ('cpf', models.CharField(max_length=11)),
                ('mae', models.CharField(max_length=128, null=True)),
                ('pai', models.CharField(max_length=128, null=True)),
            ],
            bases=('eventos.pessoa',),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='participante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='eventos.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realizadores', to='eventos.PessoaFisica'),
        ),
    ]
