# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20171023_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='pessoa_ptr',
        ),
        migrations.AlterField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realizadores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='participante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='PessoaFisica',
        ),
    ]
