# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_evento_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='festa_evento',
        ),
    ]
